version: 2.1

orbs:
  slack: circleci/slack@4.10.1

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  notify:
    executor: base
    steps:
      - checkout
      - run:
          command: |
            msg=$(./.circleci/msg.sh)
            echo "export MSG='${msg}'" >> $BASH_ENV
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${MSG}"
                  }
                }
              ]
            }

workflows:
  notify:
    jobs:
      - notify:
          filters:
            tags:
              only: /.*/
