version: 2.1

orbs:
  slack: circleci/slack@4.11.0

executors:
  base:
    docker:
      - image: cimg/base:stable

jobs:
  notify:
    executor: base
    steps:
      - checkout
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "```\nHello\nWorld\n```"
                  }
                }
              ]
            }

workflows:
  notify:
    jobs:
      - notify:
          filters:
            tags:
              only: /.*/
